### ISSUE TITLE
ZINC dataset - how many targets

### ISSUE THREAD

**Issue by giannisnik** [chrsmrrs/sparsewl#1]
Hi @chrsmrrs ,

Thank you for making this code available. 

Just a quick question. The ZINC dataset is contained in the Pytorch Geometric package (https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/zinc.html) and the task is to regress a synthetic computed property (just a single target). From your code, I noticed that you did not directly use this class of Pytorch Geometric, while from Table 1 in the paper's supplementary material, it seems that there are 12 targets instead of 1. Is this just a typo; Or did you experiment with a different copy of the dataset where there are multiple tasks?

**Comment by chrsmrrs** [comment]
Hi @giannisnik,

yes, sorry, that is a typo. It should be the same datasets as used in PyG with only one target.

Christopher
